trigger: none  

variables:
  resourceGroupName: 'cloudmonitor-rg'
  location: 'westeurope'
  parameterFile: 'main.parameters.json'
  templateFile: 'main.bicep'
  azureSubscription: 'Azure Connection'

stages:
- stage: Lint
  jobs:
    - job: LintBicep
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - script: |
            az bicep build --file $(templateFile)
          displayName: 'Bicep Lint'

- stage: Validate
  dependsOn: Lint
  jobs:
    - job: ValidateBicep
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group validate \
                --resource-group $(resourceGroupName) \
                --template-file $(templateFile) \
                --parameters @$(parameterFile)
          displayName: 'Bicep Validate'

- stage: Preview
  dependsOn: Validate
  jobs:
    - job: PreviewDeployment
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group what-if \
                --resource-group $(resourceGroupName) \
                --template-file $(templateFile) \
                --parameters @$(parameterFile)
          displayName: 'Bicep What-If (Preview)'

- stage: Deploy
  dependsOn: Preview
  jobs:
    - deployment: DeployInfra
      environment: 'production'
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: AzureCLI@2
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az deployment group create \
                      --resource-group $(resourceGroupName) \
                      --template-file $(templateFile) \
                      --parameters @$(parameterFile)
                displayName: 'Deploy Bicep to Azure'
